version: "2"

services:
  app:
    image: yulapshun/mattermost-cugcbot:new
    volumes:
      - ./cugc/data:/root/cugc/data
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
    mem_limit: ${DOCKER_MEM}
